name: Build and deploy Powershell project to Azure Function App - cipplelof
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        with:
          app-name: 'cipplelof'
          slot-name: 'Production'
          package: '.'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB1837949E224BCCBC780F31E64A5CF0 }}
          scm-do-build-during-deployment: false

      - name: Set WEBSITE_RUN_FROM_PACKAGE to storage URL
        uses: azure/CLI@v1
        with:
          inlineScript: |
            PACKAGE_URL=$(az storage blob generate-sas \
              --account-name cippstglelof \
              --account-key "${{ secrets.STORAGE_ACCOUNT_KEY }}" \
              --container-name ${{ secrets.STORAGE_CONTAINER }} \
              --name cipplelof.zip \
              --permissions r \
              --expiry 2099-01-01 \
              --https-only \
              --full-uri \
              --output tsv)
            az functionapp config appsettings set \
              --name cipplelof \
              --resource-group CIPP \
              --settings "WEBSITE_RUN_FROM_PACKAGE=$PACKAGE_URL"
